image: idotdigital/docker-build-container:latest

deploy:
  stage: deploy
  only:
    - master
  tags:
    - linux
  before_script:
    - export GITLAB_AUTH_TOKEN=$CI_JOB_TOKEN
  script:
    - echo $'@idot-digital:registry=https://git.idot.digital/api/v4/packages/npm/\n//git.idot.digital/api/v4/projects/75/packages/npm/:_authToken="${GITLAB_AUTH_TOKEN}"' > .npmrc
    - pnpm install --frozen-lockfile
    - pnpm build
    - npm publish
