image: idotdigital/docker-build-container:latest

deploy:
  stage: deploy
  tags:
    - linux
  before_script:
    - echo $'@idot-digital:registry=https://git.idot.digital/api/v4/packages/npm/\n//git.idot.digital/api/v4/projects/75/packages/npm/:_authToken="${CI_JOB_TOKEN}"' > .npmrc
  script:
    - npm install --frozen-lockfile
    - npm run build
    - npm publish
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
    changes:
      - "package.json"
