image: idotdigital/docker-build-container:latest

deploy:
  stage: deploy
  tags:
    - linux
  before_script:
    - export GITLAB_AUTH_TOKEN=$CI_JOB_TOKEN
  script:
    - echo $'@idot-digital:registry=https://git.idot.digital/api/v4/packages/npm/\n//git.idot.digital/api/v4/projects/75/packages/npm/:_authToken="${GITLAB_AUTH_TOKEN}"' > .npmrc
    - npm install --frozen-lockfile
    - npm run build
    - npm publish
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
    changes:
      - "apps/docker-controller/package.json"
